/* The extension table is alphabetically sorted by the extension name string column. */

#define ANYGLL 0
#define ANYGLC 0
#define ANYES1 0
#define ANYES2 0
#define   x   ~0

//highest GLL_ver = 46, lowest GLC_ver = 30
//EXT(name_str                              , driver_cap                             ,GLL_ver,GLC_ver, gles_ver, glES2_ver, year, dependencies )
EXT(3DFX_texture_compression_FXT1           , TDFX_texture_compression_FXT1          , ANYGLL, ANYGLC,   x   ,   x   , 1999, "" )

EXT(AMD_conservative_depth                  , ARB_conservative_depth                 , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(AMD_draw_buffers_blend                  , ARB_draw_buffers_blend                 , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(AMD_performance_monitor                 , AMD_performance_monitor                , ANYGLL, ANYGLC,   x   ,   x   , 2007, "" )
EXT(AMD_pinned_memory                       , AMD_pinned_memory                      , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(AMD_seamless_cubemap_per_texture        , AMD_seamless_cubemap_per_texture       , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(AMD_shader_stencil_export               , ARB_shader_stencil_export              , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(AMD_shader_trinary_minmax               , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(AMD_vertex_shader_layer                 , AMD_vertex_shader_layer                ,   x   , ANYGLC,   x   ,   x   , 2012, "" )
EXT(AMD_vertex_shader_viewport_index        , AMD_vertex_shader_viewport_index       ,   x   , ANYGLC,   x   ,   x   , 2012, "" )

EXT(ANDROID_extension_pack_es31a            , ANDROID_extension_pack_es31a           ,   x   ,   x   ,   x   ,  31   , 2014, "" )

EXT(ANGLE_texture_compression_dxt3          , ANGLE_texture_compression_dxt          , ANYGLL, ANYGLC, ANYES1, ANYES2, 2011, "" )
EXT(ANGLE_texture_compression_dxt5          , ANGLE_texture_compression_dxt          , ANYGLL, ANYGLC, ANYES1, ANYES2, 2011, "" )

EXT(APPLE_object_purgeable                  , APPLE_object_purgeable                 , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(APPLE_packed_pixels                     , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(APPLE_texture_max_level                 , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2009, "" )

EXT(ARB_ES2_compatibility                   , ARB_ES2_compatibility                  , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_ES3_1_compatibility                 , ARB_ES3_1_compatibility                ,   x   , ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_ES3_2_compatibility                 , ARB_ES3_2_compatibility                ,   x   , ANYGLC,   x   ,   x   , 2015, "" )
EXT(ARB_ES3_compatibility                   , ARB_ES3_compatibility                  ,  33   ,  33   ,   x   ,   x   , 2012, "ARB_ES2_compatibility&&ARB_invalidate_subdata&&ARB_texture_storage&&OES_compressed_*" )
EXT(ARB_arrays_of_arrays                    , ARB_arrays_of_arrays                   ,  12   ,  12   ,   x   ,   x   , 2012, "" )
EXT(ARB_base_instance                       , ARB_base_instance                      ,  20   ,  20   ,   x   ,   x   , 2011, "OpenGL31||ARB_draw_instanced" )
EXT(ARB_bindless_texture                    , ARB_bindless_texture                   , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_blend_func_extended                 , ARB_blend_func_extended                , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_buffer_storage                      , ARB_buffer_storage                     , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
//EXT(ARB_cl_event                            , ARB_cl_event                           ,  31   ,  31   ,   x   ,   x   , 2013, "GL_ARB_sync" )
EXT(ARB_clear_buffer_object                 , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_clear_texture                       , ARB_clear_texture                      , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_clip_control                        , ARB_clip_control                       , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_color_buffer_float                  , ARB_color_buffer_float                 , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(ARB_compatibility                       , ARB_compatibility                      , ANYGLL,   x   ,   x   ,   x   , 2009, "" )
EXT(ARB_compressed_texture_pixel_storage    , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(ARB_compute_shader                      , ARB_compute_shader                     ,  42   ,  42   ,   x   ,   x   , 2012, "" )
EXT(ARB_compute_variable_group_size         , ARB_compute_variable_group_size        ,  42   ,  42   ,   x   ,   x   , 2013, "ARB_compute_shader||OpenGL42" )
EXT(ARB_conditional_render_inverted         , ARB_conditional_render_inverted        , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_conservative_depth                  , ARB_conservative_depth                 ,  30   ,  30   ,   x   ,   x   , 2011, "" )
EXT(ARB_copy_buffer                         , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_copy_image                          , ARB_copy_image                         ,  11   ,  11   ,   x   ,   x   , 2012, "" )
EXT(ARB_cull_distance                       , ARB_cull_distance                      ,  30   ,  30   ,   x   ,   x   , 2014, "" )
EXT(ARB_debug_output                        , dummy_true                             ,  11   ,  11   ,   x   ,   x   , 2009, "" )
EXT(ARB_depth_buffer_float                  , ARB_depth_buffer_float                 , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_depth_clamp                         , ARB_depth_clamp                        , ANYGLL, ANYGLC,   x   ,   x   , 2003, "" )
EXT(ARB_depth_texture                       , ARB_depth_texture                      ,  11   ,   x   ,   x   ,   x   , 2001, "" )
EXT(ARB_derivative_control                  , ARB_derivative_control                 ,  40   ,  40   ,   x   ,   x   , 2014, "" )
EXT(ARB_direct_state_access                 , dummy_true                             ,   x   ,  20   ,   x   ,   x   , 2014, "" )
EXT(ARB_draw_buffers                        , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )
EXT(ARB_draw_buffers_blend                  , ARB_draw_buffers_blend                 , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_draw_elements_base_vertex           , ARB_draw_elements_base_vertex          , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_draw_indirect                       , ARB_draw_indirect                      ,   x   ,  31   ,   x   ,   x   , 2010, "" )
EXT(ARB_draw_instanced                      , ARB_draw_instanced                     ,  20   ,  20   ,   x   ,   x   , 2008, "EXT_gpu_shader4||NV_vertex_program4||OpenGL30" )
EXT(ARB_enhanced_layouts                    , ARB_enhanced_layouts                   ,  31   ,  31   ,   x   ,   x   , 2013, "" )
EXT(ARB_explicit_attrib_location            , ARB_explicit_attrib_location           , ANYGLL, ANYGLC,   x   ,   x   , 2009, "GL_ARB_vertex_shader" )
EXT(ARB_explicit_uniform_location           , ARB_explicit_uniform_location          , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_fragment_coord_conventions          , ARB_fragment_coord_conventions         , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_fragment_layer_viewport             , ARB_fragment_layer_viewport            ,   x   , ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_fragment_program                    , ARB_fragment_program                   , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(ARB_fragment_program_shadow             , ARB_fragment_program_shadow            , ANYGLL,   x   ,   x   ,   x   , 2003, "" )
EXT(ARB_fragment_shader                     , ARB_fragment_shader                    , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )
//EXT(ARB_fragment_shader_interlock           , ARB_fragment_shader_interlock          ,  42   ,  42   ,   x   ,   x   , 2015, "" )
EXT(ARB_framebuffer_no_attachments          , ARB_framebuffer_no_attachments         ,  11   ,  11   ,   x   ,   x   , 2012, "ARB_framebuffer_object" )
EXT(ARB_framebuffer_object                  , ARB_framebuffer_object                 ,  11   ,  11   ,   x   ,   x   , 2005, "" )
EXT(ARB_framebuffer_sRGB                    , EXT_framebuffer_sRGB                   , ANYGLL, ANYGLC,   x   ,   x   , 1998, "" )
EXT(ARB_get_program_binary                  , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_get_texture_sub_image               , dummy_true                             ,  20   ,  20   ,   x   ,   x   , 2014, "" )
EXT(ARB_gl_spirv                            , ARB_gl_spirv                           ,   x   ,  33   ,   x   ,   x   , 2016, "" )
EXT(ARB_gpu_shader5                         , ARB_gpu_shader5                        ,  30   ,  30   ,   x   ,   x   , 2010, "" )
EXT(ARB_gpu_shader_fp64                     , ARB_gpu_shader_fp64                    ,  32   ,  32   ,   x   ,   x   , 2010, "" )
EXT(ARB_gpu_shader_int64                    , ARB_gpu_shader_int64                   ,   x   ,  40   ,   x   ,   x   , 2015, "" )
EXT(ARB_half_float_pixel                    , dummy_true                             ,  15   ,  15   ,   x   ,   x   , 2003, "" )
EXT(ARB_half_float_vertex                   , ARB_half_float_vertex                  , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_indirect_parameters                 , ARB_indirect_parameters                ,   x   ,  42   ,   x   ,   x   , 2013, "" )
EXT(ARB_instanced_arrays                    , ARB_instanced_arrays                   , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_internalformat_query                , ARB_internalformat_query               , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(ARB_internalformat_query2               , ARB_internalformat_query2              ,  20   ,  20   ,   x   ,  20   , 2013, "ARB_internalformat_query" )
EXT(ARB_invalidate_subdata                  , dummy_true                             ,  20   ,  20   ,   x   ,   x   , 2012, "" )
EXT(ARB_map_buffer_alignment                , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(ARB_map_buffer_range                    , ARB_map_buffer_range                   , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_multi_bind                          , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_multi_draw_indirect                 , ARB_draw_indirect                      ,   x   , ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_multisample                         , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1994, "" )
EXT(ARB_multitexture                        , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1998, "" )
EXT(ARB_occlusion_query                     , ARB_occlusion_query                    , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(ARB_occlusion_query2                    , ARB_occlusion_query2                   , ANYGLL, ANYGLC,   x   ,   x   , 2003, "" )
EXT(ARB_pipeline_statistics_query           , ARB_pipeline_statistics_query          , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_pixel_buffer_object                 , EXT_pixel_buffer_object                , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(ARB_point_parameters                    , EXT_point_parameters                   , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(ARB_point_sprite                        , ARB_point_sprite                       , ANYGLL, ANYGLC,   x   ,   x   , 2003, "" )
EXT(ARB_polygon_offset_clamp                , ARB_polygon_offset_clamp               ,  33   ,  33   ,   x   ,   x   , 2017, "" )
EXT(ARB_post_depth_coverage                 , ARB_post_depth_coverage                ,   x   , ANYGLC,   x   ,   x   , 2015, "" )
EXT(ARB_program_interface_query             , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_provoking_vertex                    , EXT_provoking_vertex                   , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_query_buffer_object                 , ARB_query_buffer_object                , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_robust_buffer_access_behavior       , ARB_robust_buffer_access_behavior      , ANYGLL, ANYGLC,   x   ,   x   , 2012, "ARB_robustness extension" )
EXT(ARB_robustness                          , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_sample_shading                      , ARB_sample_shading                     ,  20   ,  20   ,   x   ,   x   , 2009, "" )
//EXT(ARB_sample_locations                    , ARB_sample_locations                   ,   x   ,   x   ,   x   ,   x   , 2009
EXT(ARB_sampler_objects                     , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_seamless_cube_map                   , ARB_seamless_cube_map                  ,  11   ,  11   ,   x   ,   x   , 2009, "ARB_texture_cube_map" )
EXT(ARB_seamless_cubemap_per_texture        , AMD_seamless_cubemap_per_texture       , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_separate_shader_objects             , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2010, "ARB_shader_objects" )
EXT(ARB_shader_atomic_counter_ops           , ARB_shader_atomic_counter_ops          , ANYGLL, ANYGLC,   x   ,   x   , 2015, "" )
EXT(ARB_shader_atomic_counters              , ARB_shader_atomic_counters             , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(ARB_shader_ballot                       , ARB_shader_ballot                      , ANYGLL, ANYGLC,   x   ,   x   , 2015, "" )
EXT(ARB_shader_bit_encoding                 , ARB_shader_bit_encoding                , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_shader_clock                        , ARB_shader_clock                       , ANYGLL, ANYGLC,   x   ,   x   , 2015, "" )
EXT(ARB_shader_draw_parameters              , ARB_shader_draw_parameters             , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_shader_group_vote                   , ARB_shader_group_vote                  ,  42   ,  42   ,   x   ,   x   , 2013, "" )
EXT(ARB_shader_image_load_store             , ARB_shader_image_load_store            ,  30   ,  30   ,   x   ,   x   , 2011, "" )
EXT(ARB_shader_image_size                   , ARB_shader_image_size                  ,  42   ,  42   ,   x   ,   x   , 2012, "" )
EXT(ARB_shader_objects                      , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )
EXT(ARB_shader_precision                    , ARB_shader_precision                   , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_shader_stencil_export               , ARB_shader_stencil_export              , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_shader_storage_buffer_object        , ARB_shader_storage_buffer_object       , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_shader_subroutine                   , dummy_true                             ,   x   , ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_shader_texture_image_samples        , ARB_shader_texture_image_samples       , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_shader_texture_lod                  , ARB_shader_texture_lod                 , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_shader_viewport_layer_array         , ARB_shader_viewport_layer_array        ,   x   , ANYGLC,   x   ,   x   , 2015, "" )
EXT(ARB_shading_language_100                , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2003, "" )
EXT(ARB_shading_language_420pack            , ARB_shading_language_420pack           , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(ARB_shading_language_packing            , ARB_shading_language_packing           , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(ARB_shadow                              , ARB_shadow                             , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
//EXT(ARB_shadow_ambient                      , ARB_shadow_ambient                     ,  11   ,   x   ,   x   ,   x   , 2001, "ARB_shadow" )
EXT(ARB_sparse_buffer                       , ARB_sparse_buffer                      , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
//EXT(ARB_sparse_texture                      , ARB_sparse_texture                     ,  11   ,  11   ,   x   ,   x   , 2014, "" )
//EXT(ARB_sparse_texture2                     , ARB_sparse_texture2                    ,  11   ,  11   ,   x   ,   x   , 2014, "ARB_sparse_texture" )
//EXT(ARB_sparse_texture_clamp                , ARB_sparse_texture_clamp               ,  11   ,  11   ,   x   ,   x   , 2014, "ARB_sparse_texture2" )
EXT(ARB_stencil_texturing                   , ARB_stencil_texturing                  ,  11   ,  11   ,   x   ,   x   , 2012, "" )
EXT(ARB_sync                                , ARB_sync                               ,  31   ,  31   ,   x   ,   x   , 2003, "" )
EXT(ARB_tessellation_shader                 , ARB_tessellation_shader                ,   x   , ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_barrier                     , NV_texture_barrier                     , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_texture_border_clamp                , ARB_texture_border_clamp               , ANYGLL,   x   ,   x   ,   x   , 2000, "" )
EXT(ARB_texture_buffer_object               , ARB_texture_buffer_object              , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_texture_buffer_object_rgb32         , ARB_texture_buffer_object_rgb32        , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_buffer_range                , ARB_texture_buffer_range               , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_texture_compression                 , dummy_true                             ,  11   ,   x   ,   x   ,   x   , 2000, "" )
EXT(ARB_texture_compression_bptc            , ARB_texture_compression_bptc           ,  11   ,  11   ,   x   ,   x   , 2010, "" )
EXT(ARB_texture_compression_rgtc            , ARB_texture_compression_rgtc           ,  11   ,  11   ,   x   ,   x   , 2004, "ARB_texture_compression" )
EXT(ARB_texture_cube_map                    , ARB_texture_cube_map                   , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(ARB_texture_cube_map_array              , ARB_texture_cube_map_array             , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_env_add                     , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(ARB_texture_env_combine                 , ARB_texture_env_combine                , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(ARB_texture_env_crossbar                , ARB_texture_env_crossbar               ,  11   ,   x   ,   x   ,   x   , 2001, "" )
EXT(ARB_texture_env_dot3                    , ARB_texture_env_dot3                   , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(ARB_texture_filter_anisotropic          , ARB_texture_filter_anisotropic         , ANYGLL, ANYGLC,   x   ,   x   , 2017, "" )
EXT(ARB_texture_float                       , ARB_texture_float                      , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(ARB_texture_gather                      , ARB_texture_gather                     , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_mirror_clamp_to_edge        , ARB_texture_mirror_clamp_to_edge       ,  14   ,  14   ,   x   ,   x   , 2013, "" )
EXT(ARB_texture_mirrored_repeat             , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(ARB_texture_multisample                 , ARB_texture_multisample                , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_non_power_of_two            , ARB_texture_non_power_of_two           , ANYGLL, ANYGLC,   x   ,   x   , 2003, "" )
EXT(ARB_texture_query_levels                , ARB_texture_query_levels               ,  30   ,  30   ,   x   ,   x   , 2012, "" )
EXT(ARB_texture_query_lod                   , ARB_texture_query_lod                  , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_rectangle                   , NV_texture_rectangle                   ,  11   ,  11   ,   x   ,   x   , 2004, "" )
EXT(ARB_texture_rg                          , ARB_texture_rg                         , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_texture_rgb10_a2ui                  , ARB_texture_rgb10_a2ui                 , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_texture_stencil8                    , ARB_texture_stencil8                   , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_texture_storage                     , dummy_true                             ,  12   ,  12   ,   x   ,   x   , 2011, "" )
EXT(ARB_texture_storage_multisample         , ARB_texture_multisample                , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_texture_swizzle                     , EXT_texture_swizzle                    , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(ARB_texture_view                        , ARB_texture_view                       , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_timer_query                         , ARB_timer_query                        , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_transform_feedback2                 , ARB_transform_feedback2                , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_transform_feedback3                 , ARB_transform_feedback3                , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_transform_feedback_instanced        , ARB_transform_feedback_instanced       ,  20   ,  20   ,   x   ,   x   , 2011, "(OpenGL||ARB_transform_feedback2)&&(OpenGL31||ARB_draw_instanced)" )
EXT(ARB_transform_feedback_overflow_query   , ARB_transform_feedback_overflow_query  , ANYGLL, ANYGLC,   x   ,   x   , 2014, "" )
EXT(ARB_transpose_matrix                    , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(ARB_uniform_buffer_object               , ARB_uniform_buffer_object              , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_vertex_array_bgra                   , EXT_vertex_array_bgra                  ,  11   ,  11   ,   x   ,   x   , 2008, "" )
EXT(ARB_vertex_array_object                 , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(ARB_vertex_attrib_64bit                 , ARB_vertex_attrib_64bit                ,   x   ,  32   ,   x   ,   x   , 2010, "ARB_gpu_shader_fp64" )
EXT(ARB_vertex_attrib_binding               , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2012, "" )
EXT(ARB_vertex_buffer_object                , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2003, "" )
EXT(ARB_vertex_program                      , ARB_vertex_program                     ,  13   ,   x   ,   x   ,   x   , 2002, "" )
EXT(ARB_vertex_shader                       , ARB_vertex_shader                      , ANYGLL, ANYGLC,   x   ,   x   , 2002, "ARB_shader_objects" )
EXT(ARB_vertex_type_10f_11f_11f_rev         , ARB_vertex_type_10f_11f_11f_rev        , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )
EXT(ARB_vertex_type_2_10_10_10_rev          , ARB_vertex_type_2_10_10_10_rev         , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ARB_viewport_array                      , ARB_viewport_array                     ,   x   , ANYGLC,   x   ,   x   , 2010, "" )
EXT(ARB_window_pos                          , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2001, "" )

EXT(ATI_blend_equation_separate             , EXT_blend_equation_separate            , ANYGLL, ANYGLC,   x   ,   x   , 2003, "" )
EXT(ATI_draw_buffers                        , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(ATI_fragment_shader                     , ATI_fragment_shader                    , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(ATI_meminfo                             , ATI_meminfo                            , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(ATI_separate_stencil                    , ATI_separate_stencil                   , ANYGLL,   x   ,   x   ,   x   , 2006, "" )
EXT(ATI_texture_compression_3dc             , ATI_texture_compression_3dc            , ANYGLL,   x   ,   x   ,   x   , 2004, "" )
EXT(ATI_texture_env_combine3                , ATI_texture_env_combine3               , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(ATI_texture_float                       , ARB_texture_float                      , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )
EXT(ATI_texture_mirror_once                 , ATI_texture_mirror_once                , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )

EXT(EXT_abgr                                , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 1995, "" )
EXT(EXT_base_instance                       , ARB_base_instance                      ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(EXT_bgra                                , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_blend_color                         , EXT_blend_color                        , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_blend_equation_separate             , EXT_blend_equation_separate            , ANYGLL, ANYGLC,   x   ,   x   , 2003, "" )
EXT(EXT_blend_func_extended                 , ARB_blend_func_extended                ,   x   ,   x   ,   x   , ANYES2, 2015, "" )
EXT(EXT_blend_func_separate                 , EXT_blend_func_separate                , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(EXT_blend_minmax                        , EXT_blend_minmax                       , ANYGLL,   x   , ANYES1, ANYES2, 1995, "" )
EXT(EXT_blend_subtract                      , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_buffer_storage                      , ARB_buffer_storage                     ,   x   ,   x   ,   x   ,  31   , 2015, "" )
EXT(EXT_clip_cull_distance                  , ARB_cull_distance                      ,   x   ,   x   ,   x   ,  30   , 2016, "" )
EXT(EXT_color_buffer_float                  , dummy_true                             ,   x   ,   x   ,   x   ,  30   , 2013, "" )
EXT(EXT_compiled_vertex_array               , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1996, "" )
EXT(EXT_compressed_ETC1_RGB8_sub_texture    , OES_compressed_ETC1_RGB8_texture       ,   x   ,   x   , ANYES1, ANYES2, 2014, "" )
EXT(EXT_copy_image                          , OES_copy_image                         ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(EXT_copy_texture                        , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_depth_bounds_test                   , EXT_depth_bounds_test                  , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )
EXT(EXT_discard_framebuffer                 , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2009, "" )
EXT(EXT_disjoint_timer_query                , EXT_disjoint_timer_query               ,   x   ,   x   ,   x   , ANYES2, 2016, "" )
EXT(EXT_draw_buffers                        , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2012, "" )
EXT(EXT_draw_buffers2                       , EXT_draw_buffers2                      , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(EXT_draw_buffers_indexed                , ARB_draw_buffers_blend                 ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(EXT_draw_elements_base_vertex           , ARB_draw_elements_base_vertex          ,   x   ,   x   ,   x   , ANYES2, 2014, "" )
EXT(EXT_draw_instanced                      , ARB_draw_instanced                     , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(EXT_draw_range_elements                 , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(EXT_fog_coord                           , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(EXT_frag_depth                          , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2010, "" )
EXT(EXT_framebuffer_blit                    , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2005, "" )
EXT(EXT_framebuffer_multisample             , EXT_framebuffer_multisample            , ANYGLL, ANYGLC,   x   ,   x   , 2005, "" )
EXT(EXT_framebuffer_multisample_blit_scaled , EXT_framebuffer_multisample_blit_scaled, ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(EXT_framebuffer_object                  , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2000, "" )
EXT(EXT_framebuffer_sRGB                    , EXT_framebuffer_sRGB                   , ANYGLL, ANYGLC,   x   ,   x   , 1998, "" )
EXT(EXT_geometry_point_size                 , OES_geometry_shader                    ,   x   ,   x   ,   x   ,  31   , 2015, "" )
EXT(EXT_geometry_shader                     , OES_geometry_shader                    ,   x   ,   x   ,   x   ,  31   , 2015, "" )
EXT(EXT_gpu_program_parameters              , EXT_gpu_program_parameters             , ANYGLL,   x   ,   x   ,   x   , 2006, "" )
EXT(EXT_gpu_shader4                         , EXT_gpu_shader4                        , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(EXT_gpu_shader5                         , ARB_gpu_shader5                        ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(EXT_map_buffer_range                    , ARB_map_buffer_range                   ,   x   ,   x   , ANYES1, ANYES2, 2012, "" )
EXT(EXT_memory_object                       , EXT_memory_object                      , ANYGLL, ANYGLC,   x   , ANYES2, 2017, "" )
EXT(EXT_memory_object_fd                    , EXT_memory_object_fd                   , ANYGLL, ANYGLC,   x   , ANYES2, 2017, "" )
EXT(EXT_multi_draw_arrays                   , dummy_true                             , ANYGLL,   x   , ANYES1, ANYES2, 1999, "" )
EXT(EXT_occlusion_query_boolean             , ARB_occlusion_query                    ,   x   ,   x   ,   x   , ANYES2, 2001, "" )
EXT(EXT_packed_depth_stencil                , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2005, "" )
EXT(EXT_packed_float                        , EXT_packed_float                       , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(EXT_packed_pixels                       , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(EXT_pixel_buffer_object                 , EXT_pixel_buffer_object                , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(EXT_point_parameters                    , EXT_point_parameters                   , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(EXT_polygon_offset_clamp                , ARB_polygon_offset_clamp               , ANYGLL, ANYGLC, ANYES1, ANYES2, 2014, "" )
EXT(EXT_primitive_bounding_box              , OES_primitive_bounding_box             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(EXT_provoking_vertex                    , EXT_provoking_vertex                   , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(EXT_read_format_bgra                    , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2009, "" )
EXT(EXT_rescale_normal                      , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(EXT_robustness                          , KHR_robustness                         ,   x   ,   x   ,    x  , ANYES2, 2011, "" )
EXT(EXT_secondary_color                     , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(EXT_semaphore                           , EXT_semaphore                          , ANYGLL, ANYGLC,   x   , ANYES2, 2017, "" )
EXT(EXT_semaphore_fd                        , EXT_semaphore_fd                       , ANYGLL, ANYGLC,   x   , ANYES2, 2017, "" )
EXT(EXT_separate_shader_objects             , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2013, "" )
EXT(EXT_separate_specular_color             , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(EXT_shader_framebuffer_fetch            , EXT_shader_framebuffer_fetch           , ANYGLL, ANYGLC,   x   , ANYES2, 2013, "" )
EXT(EXT_shader_framebuffer_fetch_non_coherent, EXT_shader_framebuffer_fetch_non_coherent, ANYGLL, ANYGLC,  x, ANYES2 , 2018, "" )
EXT(EXT_shader_integer_mix                  , EXT_shader_integer_mix                 , ANYGLL, ANYGLC,   x   ,  30   , 2013, "" )
EXT(EXT_shader_io_blocks                    , dummy_true                             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(EXT_shader_samples_identical            , EXT_shader_samples_identical           , ANYGLL, ANYGLC,   x   ,  31   , 2015, "" )
EXT(EXT_shadow_funcs                        , ARB_shadow                             , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(EXT_stencil_two_side                    , EXT_stencil_two_side                   , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(EXT_stencil_wrap                        , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(EXT_subtexture                          , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_tessellation_point_size             , ARB_tessellation_shader                ,   x   ,   x   ,   x   ,  31   , 2013, "" )
EXT(EXT_tessellation_shader                 , ARB_tessellation_shader                ,   x   ,   x   ,   x   ,  31   , 2013, "" )
EXT(EXT_texture                             , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1996, "" )
EXT(EXT_texture3D                           , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1996, "" )
EXT(EXT_texture_array                       , EXT_texture_array                      , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(EXT_texture_border_clamp                , ARB_texture_border_clamp               ,   x   ,   x   ,   x   , ANYES2, 2014, "" )
EXT(EXT_texture_buffer                      , OES_texture_buffer                     ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(EXT_texture_compression_dxt1            , ANGLE_texture_compression_dxt          , ANYGLL, ANYGLC, ANYES1, ANYES2, 2004, "" )
EXT(EXT_texture_compression_latc            , EXT_texture_compression_latc           , ANYGLL,   x   ,   x   ,   x   , 2006, "" )
EXT(EXT_texture_compression_rgtc            , ARB_texture_compression_rgtc           , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(EXT_texture_compression_s3tc            , EXT_texture_compression_s3tc           , ANYGLL, ANYGLC,   x   ,   x   , 2000, "" )
EXT(EXT_texture_cube_map                    , ARB_texture_cube_map                   , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(EXT_texture_cube_map_array              , OES_texture_cube_map_array             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(EXT_texture_edge_clamp                  , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(EXT_texture_env_add                     , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(EXT_texture_env_combine                 , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2000, "" )
EXT(EXT_texture_env_dot3                    , EXT_texture_env_dot3                   , ANYGLL,   x   ,   x   ,   x   , 2000, "" )
EXT(EXT_texture_filter_anisotropic          , EXT_texture_filter_anisotropic         , ANYGLL, ANYGLC, ANYES1, ANYES2, 1999, "" )
EXT(EXT_texture_format_BGRA8888             , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(EXT_texture_integer                     , EXT_texture_integer                    , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(EXT_texture_lod_bias                    , dummy_true                             , ANYGLL,   x   , ANYES1,   x   , 1999, "" )
EXT(EXT_texture_mirror_clamp                , EXT_texture_mirror_clamp               , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(EXT_texture_norm16                      , dummy_true                             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(EXT_texture_object                      , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_texture_rectangle                   , NV_texture_rectangle                   , ANYGLL,   x   ,   x   ,   x   , 2004, "" )
EXT(EXT_texture_rg                          , ARB_texture_rg                         ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(EXT_texture_sRGB                        , EXT_texture_sRGB                       , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(EXT_texture_sRGB_decode                 , EXT_texture_sRGB_decode                , ANYGLL, ANYGLC,   x   ,  30   , 2006, "" )
EXT(EXT_texture_shared_exponent             , EXT_texture_shared_exponent            , ANYGLL, ANYGLC,   x   ,   x   , 2004, "" )
EXT(EXT_texture_snorm                       , EXT_texture_snorm                      , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(EXT_texture_swizzle                     , EXT_texture_swizzle                    , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(EXT_texture_type_2_10_10_10_REV         , EXT_texture_type_2_10_10_10_REV        ,   x   ,   x   ,   x   , ANYES2, 2008, "" )
EXT(EXT_timer_query                         , EXT_timer_query                        , ANYGLL, ANYGLC,   x   ,   x   , 2006, "" )
EXT(EXT_transform_feedback                  , EXT_transform_feedback                 , ANYGLL, ANYGLC,   x   ,   x   , 2011, "" )
EXT(EXT_unpack_subimage                     , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(EXT_vertex_array                        , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1995, "" )
EXT(EXT_vertex_array_bgra                   , EXT_vertex_array_bgra                  , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(EXT_window_rectangles                   , EXT_window_rectangles                  , ANYGLL, ANYGLC,   x   ,  30   , 2016, "" )

EXT(GREMEDY_string_marker                   , GREMEDY_string_marker                  , ANYGLL, ANYGLC,   x   ,   x   , 2007, "" )

EXT(IBM_multimode_draw_arrays               , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 1998, "" )
EXT(IBM_rasterpos_clip                      , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1996, "" )
EXT(IBM_texture_mirrored_repeat             , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1998, "" )

EXT(INGR_blend_func_separate                , EXT_blend_func_separate                , ANYGLL,   x   ,   x   ,   x   , 1999, "" )

EXT(INTEL_conservative_rasterization        , INTEL_conservative_rasterization       ,   x   , ANYGLC,   x   ,  31   , 2013, "" )
EXT(INTEL_performance_query                 , INTEL_performance_query                , ANYGLL, ANYGLC,   x   , ANYES2, 2013, "" )

EXT(KHR_blend_equation_advanced             , KHR_blend_equation_advanced            , ANYGLL, ANYGLC,   x   , ANYES2, 2014, "" )
EXT(KHR_blend_equation_advanced_coherent    , KHR_blend_equation_advanced_coherent   , ANYGLL, ANYGLC,   x   , ANYES2, 2014, "" )
EXT(KHR_context_flush_control               , dummy_true                             , ANYGLL, ANYGLC,   x   , ANYES2, 2014, "" )
EXT(KHR_debug                               , dummy_true                             , ANYGLL, ANYGLC,  11   , ANYES2, 2012, "" )
EXT(KHR_no_error                            , dummy_true                             , ANYGLL, ANYGLC, ANYES1, ANYES2, 2015, "" )
EXT(KHR_robust_buffer_access_behavior       , ARB_robust_buffer_access_behavior      , ANYGLL, ANYGLC,   x   , ANYES2, 2014, "" )
EXT(KHR_robustness                          , KHR_robustness                         , ANYGLL, ANYGLC,   x   , ANYES2, 2012, "" )
EXT(KHR_texture_compression_astc_hdr        , KHR_texture_compression_astc_hdr       , ANYGLL, ANYGLC,   x   , ANYES2, 2012, "" )
EXT(KHR_texture_compression_astc_ldr        , KHR_texture_compression_astc_ldr       , ANYGLL, ANYGLC,   x   , ANYES2, 2012, "" )
EXT(KHR_texture_compression_astc_sliced_3d  , KHR_texture_compression_astc_sliced_3d , ANYGLL, ANYGLC,   x   , ANYES2, 2015, "" )

EXT(MESA_pack_invert                        , MESA_pack_invert                       , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )
EXT(MESA_shader_integer_functions           , MESA_shader_integer_functions          , ANYGLL, ANYGLC,   x   ,  30   , 2016, "" )
EXT(MESA_texture_signed_rgba                , EXT_texture_snorm                      , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(MESA_tile_raster_order                  , MESA_tile_raster_order                 , ANYGLL, ANYGLC,   x   , ANYES2, 2017, "" )
EXT(MESA_window_pos                         , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 2000, "" )
EXT(MESA_ycbcr_texture                      , MESA_ycbcr_texture                     , ANYGLL, ANYGLC,   x   ,   x   , 2002, "" )

EXT(NVX_gpu_memory_info                     , NVX_gpu_memory_info                    , ANYGLL, ANYGLC,   x   ,   x   , 2013, "" )

EXT(NV_blend_square                         , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(NV_conditional_render                   , NV_conditional_render                  , ANYGLL, ANYGLC,   x   ,   x   , 2008, "" )
EXT(NV_conservative_raster                  , NV_conservative_raster                 , ANYGLL, ANYGLC, ANYES1, ANYES2, 2015, "" )
EXT(NV_conservative_raster_dilate           , NV_conservative_raster_dilate          , ANYGLL, ANYGLC, ANYES1, ANYES2, 2015, "" )
EXT(NV_conservative_raster_pre_snap         , NV_conservative_raster_pre_snap        , ANYGLL, ANYGLC, ANYES1, ANYES2, 2017, "" )
EXT(NV_conservative_raster_pre_snap_triangles, NV_conservative_raster_pre_snap_triangles, ANYGLL, ANYGLC, ANYES1, ANYES2, 2015, "" )
EXT(NV_depth_clamp                          , ARB_depth_clamp                        , ANYGLL, ANYGLC,   x   ,   x   , 2001, "" )
EXT(NV_draw_buffers                         , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(NV_fbo_color_attachments                , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2010, "" )
EXT(NV_fill_rectangle                       , NV_fill_rectangle                      , ANYGLL, ANYGLC,   x   ,   x   , 2015, "" )
EXT(NV_fog_distance                         , NV_fog_distance                        , ANYGLL,   x   ,   x   ,   x   , 2001, "" )
EXT(NV_image_formats                        , ARB_shader_image_load_store            ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(NV_light_max_exponent                   , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(NV_packed_depth_stencil                 , dummy_true                             , ANYGLL, ANYGLC,   x   ,   x   , 2000, "" )
EXT(NV_point_sprite                         , NV_point_sprite                        , ANYGLL, ANYGLC,   x   ,   x   , 2001, "" )
EXT(NV_primitive_restart                    , NV_primitive_restart                   , ANYGLL,   x   ,   x   ,   x   , 2002, "" )
EXT(NV_read_buffer                          , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(NV_read_depth                           , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(NV_read_depth_stencil                   , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(NV_read_stencil                         , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2011, "" )
EXT(NV_texgen_reflection                    , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(NV_texture_barrier                      , NV_texture_barrier                     , ANYGLL, ANYGLC,   x   ,   x   , 2009, "" )
EXT(NV_texture_env_combine4                 , NV_texture_env_combine4                , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
EXT(NV_texture_rectangle                    , NV_texture_rectangle                   , ANYGLL,   x   ,   x   ,   x   , 2000, "" )
EXT(NV_vdpau_interop                        , NV_vdpau_interop                       , ANYGLL, ANYGLC,   x   ,   x   , 2010, "" )

EXT(OES_EGL_image                           , OES_EGL_image                          , ANYGLL, ANYGLC, ANYES1, ANYES2, 2006, "" ) /* FIXME: Mesa expects GL_OES_EGL_image to be available in OpenGL contexts. */
EXT(OES_EGL_image_external                  , OES_EGL_image_external                 ,   x   ,   x   , ANYES1, ANYES2, 2010, "" )
EXT(OES_EGL_image_external_essl3            , OES_EGL_image_external                 ,   x   ,   x   ,   x   ,  30   , 2015, "" )
EXT(OES_EGL_sync                            , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2010, "" )
EXT(OES_blend_equation_separate             , EXT_blend_equation_separate            ,   x   ,   x   , ANYES1,   x   , 2009, "" )
EXT(OES_blend_func_separate                 , EXT_blend_func_separate                ,   x   ,   x   , ANYES1,   x   , 2009, "" )
EXT(OES_blend_subtract                      , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2009, "" )
EXT(OES_byte_coordinates                    , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2002, "" )
EXT(OES_compressed_ETC1_RGB8_texture        , OES_compressed_ETC1_RGB8_texture       ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_compressed_paletted_texture         , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2003, "" )
EXT(OES_copy_image                          , OES_copy_image                         ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(OES_depth24                             , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_depth32                             , dummy_false                            ,   x   ,   x   ,   x   ,   x   , 2005, "" )
EXT(OES_depth_texture                       , ARB_depth_texture                      ,   x   ,   x   ,   x   , ANYES2, 2006, "" )
EXT(OES_depth_texture_cube_map              , OES_depth_texture_cube_map             ,   x   ,   x   ,   x   , ANYES2, 2012, "" )
EXT(OES_draw_buffers_indexed                , ARB_draw_buffers_blend                 ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(OES_draw_elements_base_vertex           , ARB_draw_elements_base_vertex          ,   x   ,   x   ,   x   , ANYES2, 2014, "" )
EXT(OES_draw_texture                        , OES_draw_texture                       ,   x   ,   x   , ANYES1,   x   , 2004, "" )
EXT(OES_element_index_uint                  , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_fbo_render_mipmap                   , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_fixed_point                         , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2002, "" )
EXT(OES_framebuffer_object                  , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2005, "" )
EXT(OES_geometry_point_size                 , OES_geometry_shader                    ,   x   ,   x   ,   x   ,  31   , 2015, "" )
EXT(OES_geometry_shader                     , OES_geometry_shader                    ,   x   ,   x   ,   x   ,  31   , 2015, "" )
EXT(OES_get_program_binary                  , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2008, "" )
EXT(OES_gpu_shader5                         , ARB_gpu_shader5                        ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_mapbuffer                           , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_packed_depth_stencil                , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2007, "" )
EXT(OES_point_size_array                    , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2004, "" )
EXT(OES_point_sprite                        , ARB_point_sprite                       ,   x   ,   x   , ANYES1,   x   , 2004, "" )
EXT(OES_primitive_bounding_box              , OES_primitive_bounding_box             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_query_matrix                        , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2003, "" )
EXT(OES_read_format                         , dummy_true                             , ANYGLL,   x   , ANYES1,   x   , 2003, "" )
EXT(OES_required_internalformat             , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2012, "" )
EXT(OES_rgb8_rgba8                          , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_sample_shading                      , OES_sample_variables                   ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(OES_sample_variables                    , OES_sample_variables                   ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(OES_shader_image_atomic                 , ARB_shader_image_load_store            ,   x   ,   x   ,   x   ,  31   , 2015, "" )
EXT(OES_shader_io_blocks                    , dummy_true                             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_shader_multisample_interpolation    , OES_sample_variables                   ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(OES_single_precision                    , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2003, "" )
EXT(OES_standard_derivatives                , OES_standard_derivatives               ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_stencil1                            , dummy_false                            ,   x   ,   x   ,   x   ,   x   , 2005, "" )
EXT(OES_stencil4                            , dummy_false                            ,   x   ,   x   ,   x   ,   x   , 2005, "" )
EXT(OES_stencil8                            , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_stencil_wrap                        , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2002, "" )
EXT(OES_surfaceless_context                 , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2012, "" )
EXT(OES_tessellation_point_size             , ARB_tessellation_shader                ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_tessellation_shader                 , ARB_tessellation_shader                ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_texture_3D                          , dummy_true                             ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_texture_border_clamp                , ARB_texture_border_clamp               ,   x   ,   x   ,   x   , ANYES2, 2014, "" )
EXT(OES_texture_buffer                      , OES_texture_buffer                     ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_texture_compression_astc            , OES_texture_compression_astc           ,   x   ,   x   , ANYES1, ANYES2, 2015, "" )
EXT(OES_texture_cube_map                    , ARB_texture_cube_map                   ,   x   ,   x   , ANYES1,   x   , 2007, "" )
EXT(OES_texture_cube_map_array              , OES_texture_cube_map_array             ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_texture_env_crossbar                , ARB_texture_env_crossbar               ,   x   ,   x   , ANYES1,   x   , 2005, "" )
EXT(OES_texture_float                       , OES_texture_float                      ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_texture_float_linear                , OES_texture_float_linear               ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_texture_half_float                  , OES_texture_half_float                 ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_texture_half_float_linear           , OES_texture_half_float_linear          ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_texture_mirrored_repeat             , dummy_true                             ,   x   ,   x   , ANYES1,   x   , 2005, "" )
EXT(OES_texture_npot                        , ARB_texture_non_power_of_two           ,   x   ,   x   , ANYES1, ANYES2, 2005, "" )
EXT(OES_texture_stencil8                    , ARB_texture_stencil8                   ,   x   ,   x   ,   x   ,  30   , 2014, "" )
EXT(OES_texture_storage_multisample_2d_array, ARB_texture_multisample                ,   x   ,   x   ,   x   ,  31   , 2014, "" )
EXT(OES_vertex_array_object                 , dummy_true                             ,   x   ,   x   , ANYES1, ANYES2, 2010, "" )
EXT(OES_vertex_half_float                   , ARB_half_float_vertex                  ,   x   ,   x   ,   x   , ANYES2, 2005, "" )
EXT(OES_viewport_array                      , OES_viewport_array                     ,   x   ,   x   ,   x   ,  31   , 2010, "" )

EXT(S3_s3tc                                 , ANGLE_texture_compression_dxt          , ANYGLL, ANYGLC,   x   ,   x   , 1999, "" )

EXT(SGIS_generate_mipmap                    , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(SGIS_texture_border_clamp               , ARB_texture_border_clamp               , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(SGIS_texture_edge_clamp                 , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )
EXT(SGIS_texture_lod                        , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1997, "" )

EXT(SUN_multi_draw_arrays                   , dummy_true                             , ANYGLL,   x   ,   x   ,   x   , 1999, "" )
#undef ANYGLL
#undef ANYGLC
#undef ANYES1
#undef ANYES2
#undef  x
