traces-db:
  repo: "https://gitlab.freedesktop.org/gfx-ci/tracie/traces-db"
  commit: "fa92c25a1a5570f3119bf9bc56e310b0a3c711ac"

traces:
  - path: glmark2/desktop-blur-radius=5:effect=blur:passes=1:separable=true:windows=4.rdc
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 8867f3a41f180626d0d4b7661ff5c0f4
  - path: glmark2/jellyfish.rdc
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: e0fe979fee129c0ed42a3059d1a4e1c9
  - path: glxgears/glxgears.trace
    expectations:
      - device: gl-vmware-llvmpipe
        checksum: 02aca9b4b4ad6fd60331df6e4f87f2cd
  - path: KhronosGroup-Vulkan-Tools/vkcube.gfxr
    expectations:
      - device: vk-amd-polaris10
        checksum: 29dc9e5e55c3de331407248737c23aa7
  - path: LunarG-VulkanSamples/Hologram:-w:640:-h:480.gfxr
    expectations:
      - device: vk-amd-polaris10
        checksum: 351710942ea93d511cef39ae2d7c68da
